### ISSUE TITLE
运行一段时间后，出现的2个Bug

### ISSUE THREAD

**Issue by jiangdefucom** [Jrohy/trojan#245]
运行一段时间后，“trojan管理”页里不显示任何信息，可能是长时间运行后日志数据也越来越庞大，导致不能显示。

**Comment by Jrohy** [comment]
journalctl -f -u trojan  你可以运行下这命令， 日志显示就是调这命令通过ws来拿到信息进行展现的

**Comment by jiangdefucom** [comment]
> journalctl -f -u trojan 你可以运行下这命令， 日志显示就是调这命令通过ws来拿到信息进行展现的

感谢Jrohy大神，运行命令可以查看日志了。

另外，我的管理帐号登录不了了(VPS只装了Trojan，应该不是被盗用，连接Mysql查看也没啥异常)，运行trojan选择4Web管理重置后仍然不行，重置后显示的代码：
```

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0x83c98e]

goroutine 1 [running]:
github.com/syndtr/goleveldb/leveldb.(*DB).setClosed(...)
        /home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db_state.go:                                        225
github.com/syndtr/goleveldb/leveldb.(*DB).Close(0x0, 0x17, 0x0)
        /home/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.0/leveldb/db.go:1117 +                                        0x3e
trojan/core.SetValue(0xbd70ba, 0xa, 0xc0001f3200, 0x38, 0xd6ce20, 0xc00023a1c0)
        /home/go/trojan/core/leveldb.go:28 +0xc5
trojan/trojan.ResetAdminPass()
        /home/go/trojan/trojan/web.go:29 +0x1c5
trojan/trojan.WebMenu()
        /home/go/trojan/trojan/web.go:16 +0xfb
trojan/cmd.mainMenu()
        /home/go/trojan/cmd/root.go:63 +0x48c
trojan/cmd.glob..func6(0x1234ce0, 0x126b470, 0x0, 0x0)
        /home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x1234ce0, 0xc0000201d0, 0x0, 0x0, 0x1                                        234ce0, 0xc0000201d0)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1234ce0, 0x443a4a, 0x11f39c0, 0xc00                                        0000180)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
        /home/go/trojan/cmd/root.go:23 +0x31
main.main()
        /home/go/trojan/main.go:6 +0x20

```

**Comment by Jrohy** [comment]
可以运行trojan命令, web管理那里重置管理员密码

**Comment by jiangdefucom** [comment]
> 可以运行trojan命令, web管理那里重置管理员密码

对，就是通过这个方法重置的，不行。然后出现上面贴出的内容

**Comment by Jrohy** [comment]
你试试将/var/lib/trojan-manager这个目录改下名字，这个是leveldb的数据目录，改完文件夹名字后登入web页面应该会出现设置管理员密码的页面

**Comment by jiangdefucom** [comment]
> 你试试将/var/lib/trojan-manager这个目录改下名字，这个是leveldb的数据目录，改完文件夹名字后登入web页面应该会出现设置管理员密码的页面

感谢大神，搞定了！
