### ISSUE TITLE
[bug]系统 是 Ubuntu 20.04.1 LTS 或 Ubuntu 16.04 LTS 或 Ubuntu 18.04 LTS运行安装脚本报错

### ISSUE THREAD

**Issue by jinwyp** [Jrohy/trojan#272]
系统 是  Ubuntu 20.04.1 LTS 
或 Ubuntu 16.04 LTS 
或 Ubuntu 18.04 LTS
或 debian 9 
谷歌云 Google Cloud 主机 ，root用户

运行安装脚本后报错  (只有centos 7 成功了)

这个问题我又试了一下 用 另外一台 Windows 机器的 Subsystem for Linux（WSL子系统的Ubuntu) 的 ssh登录VPS,  运行脚本就没有问题,  而用我用 macbook pro  的终端(装了 oh my zsh ) 登录VPS 运行脚本 就有问题 , 很奇怪的问题, 

安装trojan管理程序成功!

运行命令trojan可进行trojan管理

本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.a0pRPnt1LM...
Downloading trojan 1.16.0...
######################################################################## 100.0%#=#=-#  #                                                                     
Unpacking trojan 1.16.0...
Installing trojan 1.16.0 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.a0pRPnt1LM...
Created symlink /etc/systemd/system/multi-user.target.wants/trojan.service → /etc/systemd/system/trojan.service.

1.Let's Encrypt 证书

2.自定义证书路径

panic: Error while reading terminfo data: termbox: unsupported terminal

goroutine 1 [running]:
trojan/util.getChar(0xbd7ffb, 0xb, 0x0, 0x0)
	/home/go/trojan/util/string.go:51 +0x216
trojan/util.LoopInput(0xbd7ffb, 0xb, 0xac4060, 0xc000242060, 0xc00021fd00, 0x2)
	/home/go/trojan/util/string.go:79 +0x293
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:55 +0x254
trojan/cmd.glob..func6(0x1233fc0, 0x126a750, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x1233fc0, 0xc0000201d0, 0x0, 0x0, 0x1233fc0, 0xc0000201d0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x1233fc0, 0x443a4a, 0x11f29c0, 0xc000000180)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20

**Comment by jinwyp** [comment]
还有个bug 是  通过trojan tls 重新申请证书 没有把 trojan-web 停止， 需要手动先停止  然后运行trojan tls 才可以， 否则会提示 80端口占用， acme.sh 的 standalone mode 无法重新申请证书

 

1.Let's Encrypt 证书

2.自定义证书路径

请选择使用证书方式: 1
本机ip: 35.236.176.148
请输入申请证书的域名: troweb.jinss2.cf
troweb.jinss2.cf 解析到的ip: [35.236.176.148]
停止trojan成功!
[Mon Sep  7 15:28:01 UTC 2020] Lets find script dir.
[Mon Sep  7 15:28:01 UTC 2020] _SCRIPT_='/root/.acme.sh/acme.sh'
[Mon Sep  7 15:28:01 UTC 2020] _script='/root/.acme.sh/acme.sh'
[Mon Sep  7 15:28:01 UTC 2020] _script_home='/root/.acme.sh'
[Mon Sep  7 15:28:01 UTC 2020] Using config home:/root/.acme.sh
https://github.com/acmesh-official/acme.sh
v2.8.8
[Mon Sep  7 15:28:01 UTC 2020] Running cmd: issue
[Mon Sep  7 15:28:01 UTC 2020] _main_domain='troweb.jinss2.cf'
[Mon Sep  7 15:28:01 UTC 2020] _alt_domains='no'
[Mon Sep  7 15:28:01 UTC 2020] Using config home:/root/.acme.sh
[Mon Sep  7 15:28:02 UTC 2020] default_acme_server
[Mon Sep  7 15:28:02 UTC 2020] ACME_DIRECTORY='https://acme-v02.api.letsencrypt.org/directory'
[Mon Sep  7 15:28:02 UTC 2020] DOMAIN_PATH='/root/.acme.sh/troweb.jinss2.cf_ecc'
[Mon Sep  7 15:28:02 UTC 2020] Using ACME_DIRECTORY: https://acme-v02.api.letsencrypt.org/directory
[Mon Sep  7 15:28:02 UTC 2020] _init api for server: https://acme-v02.api.letsencrypt.org/directory
[Mon Sep  7 15:28:02 UTC 2020] GET
[Mon Sep  7 15:28:02 UTC 2020] url='https://acme-v02.api.letsencrypt.org/directory'
[Mon Sep  7 15:28:02 UTC 2020] timeout=
[Mon Sep  7 15:28:02 UTC 2020] _CURL='curl -L --silent --dump-header /root/.acme.sh/http.header  -g '
[Mon Sep  7 15:28:02 UTC 2020] ret='0'
[Mon Sep  7 15:28:03 UTC 2020] ACME_KEY_CHANGE='https://acme-v02.api.letsencrypt.org/acme/key-change'
[Mon Sep  7 15:28:03 UTC 2020] ACME_NEW_AUTHZ
[Mon Sep  7 15:28:03 UTC 2020] ACME_NEW_ORDER='https://acme-v02.api.letsencrypt.org/acme/new-order'
[Mon Sep  7 15:28:03 UTC 2020] ACME_NEW_ACCOUNT='https://acme-v02.api.letsencrypt.org/acme/new-acct'
[Mon Sep  7 15:28:03 UTC 2020] ACME_REVOKE_CERT='https://acme-v02.api.letsencrypt.org/acme/revoke-cert'
[Mon Sep  7 15:28:03 UTC 2020] ACME_AGREEMENT='https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf'
[Mon Sep  7 15:28:03 UTC 2020] ACME_NEW_NONCE='https://acme-v02.api.letsencrypt.org/acme/new-nonce'
[Mon Sep  7 15:28:03 UTC 2020] ACME_VERSION='2'
[Mon Sep  7 15:28:03 UTC 2020] Le_NextRenewTime
[Mon Sep  7 15:28:03 UTC 2020] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Sep  7 15:28:03 UTC 2020] _on_before_issue
[Mon Sep  7 15:28:03 UTC 2020] _chk_main_domain='troweb.jinss2.cf'
[Mon Sep  7 15:28:03 UTC 2020] _chk_alt_domains
[Mon Sep  7 15:28:03 UTC 2020] Le_LocalAddress
[Mon Sep  7 15:28:03 UTC 2020] d='troweb.jinss2.cf'
[Mon Sep  7 15:28:03 UTC 2020] Check for domain='troweb.jinss2.cf'
[Mon Sep  7 15:28:03 UTC 2020] _currentRoot='no'
[Mon Sep  7 15:28:03 UTC 2020] Standalone mode.
[Mon Sep  7 15:28:03 UTC 2020] _checkport='80'
[Mon Sep  7 15:28:03 UTC 2020] _checkaddr
[Mon Sep  7 15:28:03 UTC 2020] Using: ss
[Mon Sep  7 15:28:03 UTC 2020] LISTEN     0      128       [::]:80                    [::]:*                   users:(("trojan",pid=2929,fd=3))
[Mon Sep  7 15:28:03 UTC 2020] tcp port 80 is already used by 80                    [
[Mon Sep  7 15:28:03 UTC 2020] Please stop it first
[Mon Sep  7 15:28:03 UTC 2020] _on_before_issue.

**Comment by jinwyp** [comment]
这个问题我又试了一下 用 另外一台 Windows 机器的 Subsystem for Linux（WSL子系统的Ubuntu) 的 ssh登录VPS,  运行脚本就没有问题,  而用我用 macbook pro  的终端(装了 oh my zsh ) 登录VPS 运行脚本 就有问题 , 很奇怪的问题,
