### ISSUE TITLE
容器內回車 trojan 報錯

### ISSUE THREAD

**Issue by vlpeng** [Jrohy/trojan#39]
以下報錯在huaweicloud GZ VM上面安裝
mysql/mysql-server:5.7 正常
jrohy/trojan 正常
web 正常可以登入

docker exec -it trojan bash 之後

[root@ecs-8749 /]# trojan
本机未安装trojan, 正在自动安装...

bash: iptables: command not found
bash: iptables: command not found
bash: iptables: command not found
bash: iptables: command not found
Failed to restart trojan.service: Unit not found.
Failed to execute operation: No such file or directory
open /usr/local/etc/trojan/config.json: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x89ad83]

goroutine 1 [running]:
trojan/core.WriterPassword(0x0, 0x0, 0x0, 0x1)
	/home/go/trojan/core/server.go:97 +0x33
trojan/cmd.check()
	/home/go/trojan/cmd/root.go:33 +0xbd
trojan/cmd.mainMenu()
	/home/go/trojan/cmd/root.go:40 +0x34
trojan/cmd.glob..func5(0x12910c0, 0x12c7810, 0x0, 0x0)
	/home/go/trojan/cmd/root.go:16 +0x20
github.com/spf13/cobra.(*Command).execute(0x12910c0, 0xc0000921b0, 0x0, 0x0, 0x12910c0, 0xc0000921b0)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:844 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x12910c0, 0x443a4a, 0x1250ac0, 0xc000000180)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/home/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
trojan/cmd.Execute()
	/home/go/trojan/cmd/root.go:23 +0x31
main.main()
	/home/go/trojan/main.go:6 +0x20

**Comment by Jrohy** [comment]
缺依赖镜像，你手动安装下yum install iptables，我今晚回去检查下依赖

**Comment by Jrohy** [comment]
之前还以为不需要iptables，特意去掉了这个依赖😂

**Comment by vlpeng** [comment]
好的，我試試

**Comment by vlpeng** [comment]
[root@ecs-8749 /]# trojan
本机未安装trojan, 正在自动安装...

Creating trojan install directory
Entering temp directory /tmp/tmp.xx3uVCjFRX...
Downloading trojan 1.15.1...


這個依賴是 curl -O https://github.com/trojan-gfw/trojan/tarball/master | sh 嗎？現在卡在這個下載...

**Comment by Jrohy** [comment]
我今晚回去测试更新下

**Comment by vlpeng** [comment]
好的，謝謝您

**Comment by vlpeng** [comment]
不知道是不是  Downloading trojan 1.15.1... 被屏掉？還是其他原因，我安裝服務器在墻內

**Comment by Jrohy** [comment]
@vlpeng 这个确实可能，墙内下github的东西不好下的

**Comment by vlpeng** [comment]
我可以把那些依賴 curl -O 下載安裝嗎？證書跟金鑰我自己放置路徑即可，不是很了解 trojan回車之後的那些命令有哪些？

**Comment by Jrohy** [comment]
@vlpeng 你可以看下脚本怎么安装的https://github.com/Jrohy/trojan/blob/master/asset/trojan-install.sh

**Comment by vlpeng** [comment]
我下載好了，也解壓成功，但是從代碼第 51 以及第52行這裡，我要怎麼去跑您這個安裝腳本？

echo Installing $NAME $VERSION to $BINARYPATH...
install -Dm755 "$NAME" "$BINARYPATH"

[https://i.imgur.com/3Z4ngw1.png](url)

**Comment by Jrohy** [comment]
curl -LO --progress-bar "$DOWNLOADURL" || wget -q --show-progress "$DOWNLOADURL" 你将脚本这一行改为`mv /root/trojan-1.15.1-linux-amd64.tar.xz .`, 然后trojan-1.15.1-linux-amd64.tar.xz这个包就放到/root目录下， 再执行脚本

**Comment by vlpeng** [comment]
不好意思，剛剛蝦忙了很久...
容器裡面找不到 trojan-install.sh，能否提示一下，再進去改那第45行，謝謝啦 ^^"

**Comment by Jrohy** [comment]
在里面下载估计也不行，得docker cp拷贝进去。还有墙内服务器装这个，可能得做好伪装，比如运行程序名改下不叫trojan，叫其他，否则有可能收到警告(当然一些小众vps可能没这问题)

**Comment by Jrohy** [comment]
docker cp trojan-install.sh trojan:容器内的目录,  你可以在外面改好再拷贝进去.

**Comment by vlpeng** [comment]
docker cp trojan-install.sh trojan:/root/
如果把這個 sh放進去容器的/root/底下，這樣可以直些執行 trojan 回車？還是 ./root/trojan-install.sh 回車 ?

**Comment by Jrohy** [comment]
要进入容器里面执行的，记得trojan-1.15.1-linux-amd64.tar.xz也拷贝进去容器里 docker cp trojan-1.15.1-linux-amd64.tar.xz trojan:/root/

**Comment by vlpeng** [comment]
trojan-install.sh 應該都可以了，但是 连接mysql失败......  
trojan-mysql 這個容器有跑起來


CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                   PORTS                               NAMES
ae0c86e6cede        mysql/mysql-server:5.7   "/entrypoint.sh mysq…"   2 minutes ago       Up 2 minutes (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp   trojan-mysql




请选择: 4
● trojan.service - trojan
   Loaded: loaded (/etc/systemd/system/trojan.service; disabled; vendor preset: disabled)
   Active: active (running) since Wed 2020-04-01 13:15:01 UTC; 4min 24s ago
     Docs: https://trojan-gfw.github.io/trojan/config
           https://trojan-gfw.github.io/trojan/
 Main PID: 214 (trojan)
   CGroup: /docker/07efd9068cbd6c12fc4be18ae90c619ee50bd03153eba104fde44915ff52dcc4/system.slice/trojan.service
           └─214 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json
           ‣ 214 /usr/bin/trojan/trojan /usr/local/etc/trojan/config.json

Apr 01 13:15:01 ecs-8749 systemd[1]: Started trojan.
Apr 01 13:15:01 ecs-8749 trojan[214]: Welcome to trojan 1.15.1
Apr 01 13:15:01 ecs-8749 trojan[214]: [2020-04-01 13:15:01] [WARN] trojan service (server) started at 0.0.0.0:443

欢迎使用trojan管理程序

1.trojan管理       	2.用户管理

3.安装管理           	4.web管理

5.查看配置           	6.生成json

请选择: 3

1.更新trojan

2.证书申请

3.安装mysql

请选择: 3

请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址:
请输入mysql root用户的密码: trojan
连接mysql失败, 请重新输入
请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址:

**Comment by vlpeng** [comment]
按照您的幫忙，真的是可以離線裝妥

[root@ecs-8749 ~]# ./trojan-install.sh
Creating trojan install directory
Entering temp directory /tmp/tmp.FgRmBqlCGA...
Downloading trojan 1.15.1...
Unpacking trojan 1.15.1...
Installing trojan 1.15.1 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.FgRmBqlCGA...
Done!
[root@ecs-8749 ~]# trojan

**Comment by vlpeng** [comment]
web 沒問題，登入沒問題，但是跟 trojan-mysql 對接，會報錯 连接mysql失败......

**Comment by vlpeng** [comment]
[blob:https://imgur.com/62075cd7-77c8-4d82-a7e2-ea247b253058](url)

**Comment by Jrohy** [comment]
mysql要在宿主机里面起mysql容器，有在宿主机安装mysql不

**Comment by Jrohy** [comment]
因为在容器里面操控不了docker(systemctl 和docker二选一)， 所以只能自己起mysql

**Comment by vlpeng** [comment]
有的
[root@ecs-8749 /]# docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS                    PORTS                               NAMES
ae0c86e6cede        mysql/mysql-server:5.7   "/entrypoint.sh mysq…"   16 minutes ago      Up 16 minutes (healthy)   0.0.0.0:3306->3306/tcp, 33060/tcp   trojan-mysql
07efd9068cbd        jrohy/trojan:latest      "init"                   25 minutes ago      Up 25 minutes                                                 trojan

**Comment by Jrohy** [comment]
我建个vps测试下，不知道有没bug这里

**Comment by Jrohy** [comment]
@vlpeng 测试了没问题， 你看下mysql有没有正常启动成功,docker logs -f trojan-mysql

**Comment by vlpeng** [comment]
有啟動
[root@ecs-8749 /]# docker logs -f trojan-mysql
[Entrypoint] MySQL Docker Image 5.7.29-1.1.15
[Entrypoint] Starting MySQL 5.7.29-1.1.15

**Comment by vlpeng** [comment]
它報這個錯誤
生成随机用户名: zCfE, 使用直接回车, 否则输入自定义用户名:
生成随机密码: qricULit, 使用直接回车, 否则输入自定义密码:
Error 1045: Access denied for user 'trojan'@'172.17.0.1' (using password: NO)

**Comment by Jrohy** [comment]
不知道后面装iptables有没问题，我测试的是镜像里面已经装好iptables了，要不重启下trojan容器

**Comment by Jrohy** [comment]
容器里面有curl的， 可以直接 curl 127.0.0.1:3306 看下有没有返回mysql的信息，还是拒绝连接

**Comment by vlpeng** [comment]
[root@ecs-8749 /]# curl 127.0.0.1:3306
5.7.29)(
        )D���f0[H.&Z+^mysql_native_password��Got packets out of order

**Comment by Jrohy** [comment]
有重启trojan容器不

**Comment by vlpeng** [comment]
重啟過了，還是會報這個
Error 1045: Access denied for user 'trojan'@'172.17.0.1' (using password: NO)
连接mysql失败!

**Comment by Jrohy** [comment]
去安装管理那里选择安装mysql，试下还会不会报连接mysql失败

**Comment by vlpeng** [comment]
> 去安装管理那里选择安装mysql，试下还会不会报连接mysql失败
還是會 报连接mysql失败

請參考以下：


请选择: 3

请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址:
请输入mysql root用户的密码: trojan
连接mysql失败, 请重新输入
请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址:

**Comment by Jrohy** [comment]
试下那个连接地址不会车填 vps ip:3306

**Comment by vlpeng** [comment]
可以

nc -v IP 3306
Connection to IP port 3306 [tcp/mysql] succeeded!
J
5.7.29~T6<���d{``E9LXmysql_native_password^[[A^[[B

**Comment by vlpeng** [comment]
會是這三個環境變數的問題嗎？

-e MYSQL_ROOT_PASSWORD=trojan -e MYSQL_ROOT_HOST=% -e MYSQL_DATABASE=trojan

**Comment by Jrohy** [comment]
有可能docker网络问题连不到宿主机的mysql, 因为是后面才安装的iptables, 如果想用127.0.0.1:3306的话，用最新镜像重建容器应该可以

**Comment by vlpeng** [comment]
我 docker pull您latest的 img了
以下是trojan的 log

Welcome to CentOS Linux 7 (Core)!

[  OK  ] Started Dispatch Password Requests to Console Directory Watch.
[  OK  ] Reached target Local Encrypted Volumes.
[  OK  ] Set up automount Arbitrary Executab...ats File System Automount Point.
[  OK  ] Started Forward Password Requests to Wall Directory Watch.
[  OK  ] Reached target Paths.
[  OK  ] Reached target Swap.
[  OK  ] Reached target Remote File Systems.
[  OK  ] Created slice Root Slice.
[  OK  ] Created slice User and Session Slice.
[  OK  ] Listening on /dev/initctl Compatibility Named Pipe.
[  OK  ] Listening on Journal Socket.
[  OK  ] Listening on Delayed Shutdown Socket.
[  OK  ] Listening on udev Control Socket.
[  OK  ] Listening on udev Kernel Socket.
[  OK  ] Created slice System Slice.
         Starting Journal Service...
[  OK  ] Reached target Slices.
[  OK  ] Created slice system-getty.slice.
         Mounting Huge Pages File System...
         Mounting Debug File System...
         Starting Load/Save Random Seed...
         Starting Rebuild Hardware Database...
         Starting Create Static Device Nodes in /dev...
         Starting Setup Virtual Console...
         Starting Apply Kernel Variables...
         Mounting Configuration File System...
[  OK  ] Mounted Huge Pages File System.
[  OK  ] Started Create Static Device Nodes in /dev.
         Starting udev Kernel Device Manager...
[  OK  ] Reached target Local File Systems (Pre).
[  OK  ] Reached target Local File Systems.
         Starting Rebuild Journal Catalog...
[  OK  ] Mounted Configuration File System.
[  OK  ] Mounted Debug File System.
[  OK  ] Started Apply Kernel Variables.
[  OK  ] Started Setup Virtual Console.
[  OK  ] Started udev Kernel Device Manager.
[  OK  ] Started Rebuild Hardware Database.
         Starting udev Coldplug all Devices...
[  OK  ] Started Rebuild Journal Catalog.
         Starting Update is Completed...
[  OK  ] Started Load/Save Random Seed.
[  OK  ] Started Update is Completed.
[  OK  ] Started udev Coldplug all Devices.
[  OK  ] Started Journal Service.
         Starting Flush Journal to Persistent Storage...
[  OK  ] Started Flush Journal to Persistent Storage.
         Starting Create Volatile Files and Directories...
[  OK  ] Started Create Volatile Files and Directories.
         Starting Update UTMP about System Boot/Shutdown...
[  OK  ] Started Update UTMP about System Boot/Shutdown.
[  OK  ] Reached target System Initialization.
[  OK  ] Started Daily Cleanup of Temporary Directories.
[  OK  ] Reached target Timers.
[  OK  ] Listening on D-Bus System Message Bus Socket.
[  OK  ] Reached target Sockets.
[  OK  ] Reached target Basic System.
         Starting Permit User Sessions...
[  OK  ] Started D-Bus System Message Bus.
         Starting Login Service...
[  OK  ] Started Permit User Sessions.
         Starting Cleanup of Temporary Directories...
[  OK  ] Started Getty on tty1.
[  OK  ] Reached target Login Prompts.
[  OK  ] Started Command Scheduler.
[  OK  ] Started Cleanup of Temporary Directories.
[  OK  ] Started Login Service.
[  OK  ] Reached target Multi-User System.
         Starting Update UTMP about System Runlevel Changes...
[  OK  ] Started Update UTMP about System Runlevel Changes.

**Comment by vlpeng** [comment]
宿主機連的到trojan-mysql

[root@ecs-8749 tmp]# docker exec -it trojan bash
[root@ecs-8749 /]# curl 127.0.0.1:3306
5.7.29
      s;'p2q~���bY/:w+b_=D8mysql_native_password��Got packets out of order[root@ecs-8749 /]#
[root@ecs-8749 /]#
[root@ecs-8749 /]# ping 172.17.0.4
PING 172.17.0.4 (172.17.0.4) 56(84) bytes of data.
64 bytes from 172.17.0.4: icmp_seq=1 ttl=64 time=0.032 ms
64 bytes from 172.17.0.4: icmp_seq=2 ttl=64 time=0.042 ms
64 bytes from 172.17.0.4: icmp_seq=3 ttl=64 time=0.040 ms
64 bytes from 172.17.0.4: icmp_seq=4 ttl=64 time=0.038 ms
^C
--- 172.17.0.4 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3087ms
rtt min/avg/max/mdev = 0.032/0.038/0.042/0.003 ms

**Comment by Jrohy** [comment]
这是系统日志是不是，重新用最新镜像能否连mysql

**Comment by vlpeng** [comment]
> 这是系统日志是不是，重新用最新镜像能否连mysql
是 docker logs -f trojan的日誌

> 重新用最新镜像能否连mysql
我用您最新鏡像了 yum install iptables -y 
Package iptables-1.4.21-33.el7.x86_64 already installed and latest version
Nothing to do

**Comment by Jrohy** [comment]
用了最新镜像就有iptables的，不用手动安装了，新镜像已经补充了依赖

**Comment by vlpeng** [comment]
我猜是不是我離線安裝，沒有跑您的 trojan 初始化安裝導致的？
但，我透過 trojan 命令對話管理，問題就發生在 安装mysql -> 连接mysql失败

**Comment by Jrohy** [comment]
真不行就用vps ip吧

**Comment by vlpeng** [comment]
用VPS IP也是一樣會 连接mysql失败

请输入mysql连接地址(格式: host:port), 默认连接地址为127.0.0.1:3306, 使用直接回车, 否则输入自定义连接地址: 139.159.207.2:3306
请输入mysql root用户的密码: trojan
连接mysql失败, 请重新输入

**Comment by vlpeng** [comment]
因為用手動安裝，就不會像初始化 trojan回車去跑您腳本的對話，會不會是因為哪個步驟沒做到所導致的？

[root@ecs-8749 ~]# sh trojan-install.sh
Creating trojan install directory
Entering temp directory /tmp/tmp.x4wvDK3c1B...
Downloading trojan 1.15.1...
Unpacking trojan 1.15.1...
Installing trojan 1.15.1 to /usr/bin/trojan/trojan...
Installing trojan server config to /usr/local/etc/trojan/config.json...
Installing trojan systemd service to /etc/systemd/system/trojan.service...
Reloading systemd daemon...
Deleting temp directory /tmp/tmp.x4wvDK3c1B...
Done!

**Comment by Jrohy** [comment]
应该不会，这是安装trojan

**Comment by Jrohy** [comment]
有没有navicat之类的工具试下连mysql, 或者进mysql容器里面用mysql命令连下mysql试试

**Comment by vlpeng** [comment]
或是您的trojan的容器可以單獨跟multi-v2ray專案一樣，單純bash的對話配置，不需要再多一個mySQL容器？
PS: 您的這兩個大作真的很不錯，都習慣您的介面了XD

**Comment by Jrohy** [comment]
@vlpeng 不行的依赖于mysql,要不重新起mysql试试，删掉mysql容器，rm -rf /home/mysql ,重新运行docker run

**Comment by vlpeng** [comment]
完全命中，已經解決啦 !!!!! 拉花，謝謝您

但是 TLS貌似握手錯誤

[2020-04-02 11:58:12] [ERROR] 127.0.0.1:64915 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:12] [INFO] 127.0.0.1:64915 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:12] [ALL] 127.0.0.1:64921 incoming connection
[2020-04-02 11:58:12] [INFO] 127.0.0.1:64921 requested connection to www.google.com:443
[2020-04-02 11:58:12] [ALL] 127.0.0.1:64921 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:13] [ERROR] 127.0.0.1:64918 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:13] [INFO] 127.0.0.1:64918 disconnected, 0 bytes received, 158 bytes sent, lasted for 1 seconds
[2020-04-02 11:58:13] [ERROR] 127.0.0.1:64921 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:13] [INFO] 127.0.0.1:64921 disconnected, 0 bytes received, 153 bytes sent, lasted for 1 seconds
[2020-04-02 11:58:15] [ALL] 127.0.0.1:64924 incoming connection
[2020-04-02 11:58:15] [INFO] 127.0.0.1:64924 requested connection to hangouts.google.com:443
[2020-04-02 11:58:15] [ALL] 127.0.0.1:64924 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:15] [ALL] 127.0.0.1:64927 incoming connection
[2020-04-02 11:58:15] [INFO] 127.0.0.1:64927 requested connection to play.google.com:443
[2020-04-02 11:58:15] [ALL] 127.0.0.1:64927 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:15] [ERROR] 127.0.0.1:64924 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:15] [INFO] 127.0.0.1:64924 disconnected, 0 bytes received, 589 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:15] [ERROR] 127.0.0.1:64927 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:15] [INFO] 127.0.0.1:64927 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:16] [ALL] 127.0.0.1:64930 incoming connection
[2020-04-02 11:58:16] [INFO] 127.0.0.1:64930 requested connection to client-s.gateway.messenger.live.com:443
[2020-04-02 11:58:16] [ALL] 127.0.0.1:64930 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64933 incoming connection
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64933 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64933 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:17] [ERROR] 127.0.0.1:64930 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64930 disconnected, 0 bytes received, 517 bytes sent, lasted for 1 seconds
[2020-04-02 11:58:17] [ERROR] 127.0.0.1:64933 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64933 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64936 incoming connection
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64936 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64936 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:17] [ERROR] 127.0.0.1:64936 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64936 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64939 incoming connection
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64939 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:17] [ALL] 127.0.0.1:64939 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:17] [ERROR] 127.0.0.1:64939 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:17] [INFO] 127.0.0.1:64939 disconnected, 0 bytes received, 154 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64942 incoming connection
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64942 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64942 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64945 incoming connection
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64945 requested connection to clients6.google.com:443
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64945 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:18] [ERROR] 127.0.0.1:64942 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64942 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:18] [ERROR] 127.0.0.1:64945 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64945 disconnected, 0 bytes received, 589 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64948 incoming connection
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64948 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64948 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:18] [ERROR] 127.0.0.1:64948 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64948 disconnected, 0 bytes received, 517 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64951 incoming connection
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64951 requested connection to ssl.gstatic.com:443
[2020-04-02 11:58:18] [ALL] 127.0.0.1:64951 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:18] [ERROR] 127.0.0.1:64951 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:18] [INFO] 127.0.0.1:64951 disconnected, 0 bytes received, 154 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:19] [ALL] 127.0.0.1:64954 incoming connection
[2020-04-02 11:58:19] [INFO] 127.0.0.1:64954 requested connection to hangouts.google.com:443
[2020-04-02 11:58:19] [ALL] 127.0.0.1:64954 trhtwhtr.test123.net is resolved to 106.11.253.86
[2020-04-02 11:58:19] [ERROR] 127.0.0.1:64954 SSL handshake failed with trhtwhtr.test123.net:443: wrong version number
[2020-04-02 11:58:19] [INFO] 127.0.0.1:64954 disconnected, 0 bytes received, 589 bytes sent, lasted for 0 seconds
[2020-04-02 11:58:20] [ALL] 127.0.0.1:64957 incoming connection
[2020-04-02 11:58:20] [INFO] 127.0.0.1:64957 requested connection to cello.client

**Comment by vlpeng** [comment]
端口443有開
放在墻內的不確定性太高了 ....
謝謝版主不吝教導以及指正，非常感謝 !!!!!
本次兩個大問題都解決了：
1) 安裝腳本 mv /root/trojan-1.15.1-linux-amd64.tar.xz .
2) 删掉mysql容器，rm -rf /home/mysql ,重新运行trojan-mysql

nc -v trhtwhtr.test123.net 443
Connection to trhtwhtr.test123.net port 443 [tcp/https] succeeded!
