### ISSUE TITLE
申请证书时报错

### ISSUE THREAD

**Issue by zxz0x01** [Jrohy/trojan#821]
Get "https://get.acme.sh": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-10-18T06:17:21-04:00 is after 2021-09-30T14:01:15Z
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x830d3b]

goroutine 1 [running]:
trojan/util.RunWebShell({0xb606aa?, 0x5?})
        /home/go/trojan/util/command.go:94 +0xfb
trojan/trojan.InstallTls()
        /home/go/trojan/trojan/install.go:113 +0x5fc
trojan/cmd.check()
        /home/go/trojan/cmd/root.go:34 +0x85
trojan/cmd.mainMenu()
        /home/go/trojan/cmd/root.go:41 +0x17
trojan/cmd.glob..func10(0xc0003ca200?, {0xb4c96d?, 0x4?, 0xb4c971?})
        /home/go/trojan/cmd/root.go:16 +0xf
github.com/spf13/cobra.(*Command).execute(0x10fe4c0, {0xc0000220a0, 0x0, 0x0})
        /home/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x10fe4c0)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
trojan/cmd.Execute()
        /home/go/trojan/cmd/root.go:23 +0x1a
main.main()
        /home/go/trojan/main.go:6 +0xf

**Comment by zxz0x01** [comment]
已解决
方法：https://blog.csdn.net/weixin_47103265/article/details/121101709
